import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { InvoiceProvider } from "@/contexts/InvoiceContexts";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { Toaster } from "@/components/ui/sonner";
import { RootLayoutContent } from "./_components/RootLayoutContent";
import { SidebarProvider } from "@/contexts/SidebarContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CredHill",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ConvexClientProvider>
          <InvoiceProvider>
            <SidebarProvider>
              <RootLayoutContent>{children}</RootLayoutContent>
            </SidebarProvider>
          </InvoiceProvider>
        </ConvexClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
